version: '3.7'

services:
  app:
    container_name: app_python
    build:
      context: .
      dockerfile: Dockerfile

  ofelia:
    image: mcuadros/ofelia:latest
    depends_on:
      - app
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      ofelia.enabled: "true"
      ofelia.job-run.app.schedule: "@every 1m"
      ofelia.job-run.app.container: "app_python"